/**
 * @author @jeancsanchez
 * @created 21/12/2023
 * Jesus loves you.
 */

FROM adoptopenjdk/openjdk11:alpine

ENV TZ=America/Fortaleza
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone


ENV SPRING_BOOT_PROFILE=$PROFILE
ENTRYPOINT [
    "java",
    "$JAVA_OPTS",
    "-Djava.security.egd=file:/dev/./urandom",
    "-jar",
    "-Dserver.port=$PORT",
    "-Dspring.profiles.active=${SPRING_BOOT_PROFILE}",
    "$(ls -1 build/libs/*jar | grep -v plain)"
]